name: Upgrade Node Version
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * *

jobs:
  upgrade:
    name: Upgrade
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      conclusion: ${{ steps.status.outputs.conclusion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Write latest version to .nvmrc file
        run: node -v > .nvmrc
      - name: Set status
        id: status
        run: echo "::set-output name=conclusion::success"
      - name: Create Patch
        run: |-
          git add .
          git diff --patch --staged > .upgrade.tmp.patch
      - name: Upload patch
        uses: actions/upload-artifact@v2
        with:
          name: .upgrade.tmp.patch
          path: .upgrade.tmp.patch
  pr:
    name: Create Pull Request
    needs: upgrade
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download patch
        uses: actions/download-artifact@v2
        with:
          name: .upgrade.tmp.patch
          path: ${{ runner.temp }}
      - name: Apply patch
        run: '[ -s ${{ runner.temp }}/.upgrade.tmp.patch ] && git apply ${{ runner.temp
          }}/.upgrade.tmp.patch || echo "Empty patch. Skipping."'
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: >-
            chore(deps): upgrade node version


            Upgrades node version. See details in [workflow run].


            [workflow run]: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}


            ------


            *Automatically created via the "upgrade-node-version" workflow*
          branch: github-actions/upgrade-node-version
          title: "chore(deps): upgrade node version"
          body: >-
            Upgrades node version. See details in [workflow run].


            [workflow run]: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}


            ------


            *Automatically created via the "upgrade-node-version" workflow*
          author: Automation <github-actions@github.com>
          committer: Automation <github-actions@github.com>
      - name: Update status check
        if: steps.create-pr.outputs.pull-request-url != ''
        run: "curl -i --fail -X POST -H \"Accept: application/vnd.github.v3+json\" -H
          \"Authorization: token ${GITHUB_TOKEN}\"
          https://api.github.com/repos/${{ github.repository }}/check-runs -d
          '{\"name\":\"build\",\"head_sha\":\"github-actions/upgrade\",\"status\
          \":\"completed\",\"conclusion\":\"${{ needs.upgrade.outputs.conclusion
          }}\",\"output\":{\"title\":\"Created via the upgrade
          node version workflow.\",\"summary\":\"Action run URL: https://github.com/${{
          github.repository }}/actions/runs/${{ github.run_id }}\"}}'"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
